PARTICIPANTS_NUMBER_OF_A_TEAM = 5
PITCHERS_NUMBER_OF_A_PLAYER = 8
RANGE_OF_RECENT_GAME = 10
YEAR_DAYS = 365
HALF_OF_YEAR_DAYS = 183      # 2월 안껴있으면 대체로 맞을듯?
STAT_MEDIAN_MULTIPLIER = 0.7
SHRINKAGE_RATE = 0.95